repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        language: python
        args: [--in-place --remove-all-unused-imports --remove-unused-variables]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
        - id: mypy
          entry: bash -c 'poetry run --mypy "$@"'
          language: system
          types: [python]
          verbose: true
          files: \.py$
          args: ["*.py$"]
        
